### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#113]
- [ ] Merge branch into main
- [ ] Update `doc/source/changelog.rst`
- [ ] Update version number in `setup.py`
- [ ] Make a release on GitHub
- [ ] Push to PyPI
