### ISSUE TITLE
TODO: Main tasks for v1.0.0

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#137]
Hi, now that we have merged #134 (various recent changes into `new-api`) and renamed `new-api` to `dev-v1.0.0`, I want to make a laundry list of major tasks code-wise that we should take care of before releasing v1.0.0 and resubmitting the paper. Feel free to check these boxes as they are completed.

@sibocw:
- [x] Test head stabilization in closed loop over complex terrain
- [x] **Improve fly following algorithm using not just T4/T5 for DN control; then merge head-stabilization-complex-terrain into dev-v1.0.0**: #139 
  - [x] Follow-up: #150 
    - [x] Further follow-up: #153 
- [x] **Merge dev-v1.0.0 into path-integration, test path integration over complex terrain using updated hybrid controller, and merge path-integration back into dev-v1.0.0** #141
  - [x] Follow-up: #145
- [x] Merge dev-cdf into dev-v1.0.0 ~~#110~~ #151 

@tkclam:
- [x] **Update RL stuff**
- [x] #140 
- [ ] ~~Merge or remove cobar-week4?~~ not until COBAR is over

@stimpfli:
- [ ] Merge new-api-grooming into dev-v1.0.0
- [x] Is new_steps already fully merged? If so, remove it
- [ ] Merge or remove fix_collisions_arena
- [x] Is automated_adhesion already fully merged? If so, remove it

**Comment by tkclam** [comment]
Let's keep `cobar-week4` until the end of the semester because some CoBaR exercises depend on it
